version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json and package-lock.json
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      - dependency-name: "node-sass"
        versions: ["<7.0.0"]
